### ISSUE TITLE
Structure project in a modular way

### ISSUE THREAD

**Issue by muhammed9865** [Skill-Sync/SkillSync-android#3]
#### Benefits
- Separation of concerns
- Reduce redundant code
- Easier management of Gradle build system

### Approach
- We need 3 modules

**Comment by mSaayeh** [comment]
We have separated the project code into three main modules `core`, `feature`, and `build-logic`, and set up the `app` module to be the navigator between screens
[More Details](https://github.com/Skill-Sync/SkillSync-android/blob/master/README.md)
